name: Build and Release

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v2.4.2
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: tools/premake5 vs2022 --no-check

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/boiii.sln

      - name: Upload ${{matrix.configuration}} bundle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{matrix.configuration}} Bundle
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii.exe
            build/bin/x64/${{matrix.configuration}}/boiii.pdb

      - name: Upload ${{matrix.configuration}} binary
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{matrix.configuration}} Binary
          path: |
            build/bin/x64/${{matrix.configuration}}/boiii.exe

  release:
    name: Release
    needs: build
    runs-on: windows-2022
    if: |
      github.repository_owner == 'Tamatoaa' &&
      github.event_name == 'push' &&
      github.ref == 'refs/tags/v*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2

      - name: Download build artifacts
        uses: actions/download-artifact@v2.2.4
        with:
          name: Release Binary
          path: build/bin/x64/Release

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Release of version ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bin/x64/Release/boiii.exe
          asset_name: boiii.exe
          asset_content_type: application/octet-stream
